#! /bin/bash

set -x
set -euo pipefail

typeset SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
typeset BUILD_DIR=${SCRIPT_DIR}

function fail {
	echo "ERROR: $*" >&2
	exit 1
}

function print_usage {
	echo "[usage] ./make_vm_img.sh"
}

if [ $# != 0 ]; then
	print_usage
	exit -1
fi

# 镜像内核版本（写死配置）：
# 当前默认 5.19.0-50-generic
# 如需切换到 5.15.0-173-generic，直接修改下面这一行即可。
# typeset kernel_version="5.19.0-50-generic"
typeset kernel_version="5.15.0-173-generic"

typeset mkosi_bin="python3 -m mkosi"
typeset mkosi_opts=("-f")

enable_systemd_service() {
	servicename="$1"

	if [ ! -d "mkosi.extra" ]; then
		fail "couldn't find mkosi.extra, are we in an unexpected CWD?"
	fi

	mkdir -p mkosi.extra/etc/systemd/system/multi-user.target.wants

	ln -sf "/usr/lib/systemd/system/${servicename}.service" \
		"mkosi.extra/etc/systemd/system/multi-user.target.wants/${servicename}.service"
}

write_proxy_env_file() {
	local file="$1"
	local shell_type="$2"
	local hp="$3"
	local hps="$4"
	local npx="$5"

	mkdir -p "$(dirname "$file")"
	case "$shell_type" in
	sh)
		cat >"$file" <<EOF
# generated by make_vm_img.sh
[ -n "${hp}" ] && export http_proxy="${hp}" && export HTTP_PROXY="${hp}"
[ -n "${hps}" ] && export https_proxy="${hps}" && export HTTPS_PROXY="${hps}"
[ -n "${npx}" ] && export no_proxy="${npx}" && export NO_PROXY="${npx}"
EOF
		;;
	fish)
		cat >"$file" <<EOF
# generated by make_vm_img.sh
if test -n "${hp}"
    set -gx http_proxy "${hp}"
    set -gx HTTP_PROXY "${hp}"
end
if test -n "${hps}"
    set -gx https_proxy "${hps}"
    set -gx HTTPS_PROXY "${hps}"
end
if test -n "${npx}"
    set -gx no_proxy "${npx}"
    set -gx NO_PROXY "${npx}"
end
EOF
		;;
	*)
		fail "unknown shell_type=$shell_type"
		;;
	esac
}

extract_proxy_value_from_bashrc() {
	local bashrc_file="$1"
	local key="$2"
	[ -f "$bashrc_file" ] || return 0
	awk -v key="$key" '
	{
		line = $0
		gsub(/\r/, "", line)
		if (line ~ "^[[:space:]]*(export[[:space:]]+)?" key "[[:space:]]*=") {
			sub("^[[:space:]]*(export[[:space:]]+)?(" key ")[[:space:]]*=[[:space:]]*", "", line)
			sub(/[[:space:]]+#.*$/, "", line)
			if ((line ~ /^".*"$/) || (line ~ /^'\''.*'\''$/)) {
				line = substr(line, 2, length(line) - 2)
			}
			print line
			exit
		}
	}
	' "$bashrc_file" || true
}

resolve_host_proxy_value() {
	local key_lower="$1"
	local key_upper="$2"
	local bashrc_file="$3"
	local host_env_file="${4:-/etc/environment}"
	local v="${!key_lower:-${!key_upper:-}}"
	if [ -n "${v}" ]; then
		echo "${v}"
		return 0
	fi
	v="$(extract_proxy_value_from_bashrc "$bashrc_file" "$key_lower")"
	if [ -n "${v}" ]; then
		echo "${v}"
		return 0
	fi
	v="$(extract_proxy_value_from_bashrc "$bashrc_file" "$key_upper")"
	if [ -n "${v}" ]; then
		echo "${v}"
		return 0
	fi
	v="$(extract_proxy_value_from_bashrc "$host_env_file" "$key_lower")"
	if [ -n "${v}" ]; then
		echo "${v}"
		return 0
	fi
	v="$(extract_proxy_value_from_bashrc "$host_env_file" "$key_upper")"
	echo "${v}"
}

write_cxlkv_proxy_environment_snippet() {
	local out="$1"
	local hp="$2"
	local hps="$3"
	local npx="$4"
	: >"$out"
	{
		[ -n "${hp}" ] && echo "http_proxy=\"${hp}\"" && echo "HTTP_PROXY=\"${hp}\""
		[ -n "${hps}" ] && echo "https_proxy=\"${hps}\"" && echo "HTTPS_PROXY=\"${hps}\""
		[ -n "${npx}" ] && echo "no_proxy=\"${npx}\"" && echo "NO_PROXY=\"${npx}\""
	} >>"$out"
}

mkdir -p ${BUILD_DIR}/mkosi.extra
mkdir -p ${BUILD_DIR}/mkosi.cache ${BUILD_DIR}/mkosi.builddir

cd ${BUILD_DIR}

# misc rootfs setup
mkdir -p mkosi.extra/root/.ssh
cp -L ~/.ssh/id_rsa.pub mkosi.extra/root/.ssh/authorized_keys
cp ~/.ssh/id_rsa.pub mkosi.extra/root/.ssh
cp ~/.ssh/id_rsa mkosi.extra/root/.ssh
touch ${BUILD_DIR}/mkosi.extra/root/.ssh/config
chmod +w ${BUILD_DIR}/mkosi.extra/root/.ssh/config || true
echo -e "Host *\n    StrictHostKeyChecking no" >>${BUILD_DIR}/mkosi.extra/root/.ssh/config
chmod 400 ${BUILD_DIR}/mkosi.extra/root/.ssh/config
chmod -R go-rwx mkosi.extra/root

source $SCRIPT_DIR/ubuntu_rootfs.sh mkosi.extra
cp -Lr ~/.bash* ${BUILD_DIR}/mkosi.extra/root/

# 宿主机代理解析策略：优先当前环境变量，其次 ~/.bashrc，再次 /etc/environment。
host_bashrc_file="${HOME}/.bashrc"
host_etc_environment="/etc/environment"
host_http_proxy="$(resolve_host_proxy_value "http_proxy" "HTTP_PROXY" "${host_bashrc_file}" "${host_etc_environment}")"
host_https_proxy="$(resolve_host_proxy_value "https_proxy" "HTTPS_PROXY" "${host_bashrc_file}" "${host_etc_environment}")"
host_no_proxy="$(resolve_host_proxy_value "no_proxy" "NO_PROXY" "${host_bashrc_file}" "${host_etc_environment}")"

# 记录宿主代理解析结果，供 postinst 在镜像收尾时回填环境变量。
host_bashrc_proxy_exports="${BUILD_DIR}/mkosi.extra/etc/cxlkv_host_bashrc_proxy_exports"
environment_proxy_snippet="${BUILD_DIR}/mkosi.extra/etc/cxlkv_environment_proxy.snippet"
mkdir -p "${BUILD_DIR}/mkosi.extra/etc"
: >"${host_bashrc_proxy_exports}"
{
	[ -n "${host_http_proxy}" ] && echo "http_proxy=${host_http_proxy}" && echo "HTTP_PROXY=${host_http_proxy}"
	[ -n "${host_https_proxy}" ] && echo "https_proxy=${host_https_proxy}" && echo "HTTPS_PROXY=${host_https_proxy}"
	[ -n "${host_no_proxy}" ] && echo "no_proxy=${host_no_proxy}" && echo "NO_PROXY=${host_no_proxy}"
} >>"${host_bashrc_proxy_exports}"
rm -f "${environment_proxy_snippet}" || true
if [ -n "${host_http_proxy}" ] || [ -n "${host_https_proxy}" ] || [ -n "${host_no_proxy}" ]; then
	write_cxlkv_proxy_environment_snippet "${environment_proxy_snippet}" \
		"${host_http_proxy}" "${host_https_proxy}" "${host_no_proxy}"
fi

# 将宿主机代理配置显式写入镜像内 apt 配置，提升构建阶段下载速度。
if [ -n "${host_http_proxy}" ] || [ -n "${host_https_proxy}" ]; then
	mkdir -p ${BUILD_DIR}/mkosi.extra/etc/apt/apt.conf.d
	{
		[ -n "${host_http_proxy}" ] && echo "Acquire::http::Proxy \"${host_http_proxy}\";"
		[ -n "${host_https_proxy}" ] && echo "Acquire::https::Proxy \"${host_https_proxy}\";"
	} >${BUILD_DIR}/mkosi.extra/etc/apt/apt.conf.d/01proxy
else
	rm -f ${BUILD_DIR}/mkosi.extra/etc/apt/apt.conf.d/01proxy || true
fi

# 若宿主机设置了代理，则预置到镜像内基础环境文件（最终以 postinst 收尾结果为准）。
rm -f ${BUILD_DIR}/mkosi.extra/etc/profile.d/99-proxy.sh || true
rm -f ${BUILD_DIR}/mkosi.extra/etc/fish/conf.d/99-proxy.fish || true
if [ -n "${host_http_proxy}" ] || [ -n "${host_https_proxy}" ] || [ -n "${host_no_proxy}" ]; then
	mkdir -p ${BUILD_DIR}/mkosi.extra/etc/profile.d
	mkdir -p ${BUILD_DIR}/mkosi.extra/etc/fish/conf.d
	mkdir -p ${BUILD_DIR}/mkosi.extra/etc

	write_proxy_env_file "${BUILD_DIR}/mkosi.extra/etc/profile.d/99-proxy.sh" "sh" \
		"${host_http_proxy}" "${host_https_proxy}" "${host_no_proxy}"
	chmod 0644 "${BUILD_DIR}/mkosi.extra/etc/profile.d/99-proxy.sh"

	write_proxy_env_file "${BUILD_DIR}/mkosi.extra/etc/fish/conf.d/99-proxy.fish" "fish" \
		"${host_http_proxy}" "${host_https_proxy}" "${host_no_proxy}"
	chmod 0644 "${BUILD_DIR}/mkosi.extra/etc/fish/conf.d/99-proxy.fish"

	# /etc/environment 与片段文件字节一致，供 postinst 优先合并。
	touch "${BUILD_DIR}/mkosi.extra/etc/environment"
	sed -i '/^http_proxy=/d;/^HTTP_PROXY=/d;/^https_proxy=/d;/^HTTPS_PROXY=/d;/^no_proxy=/d;/^NO_PROXY=/d;/^all_proxy=/d;/^ALL_PROXY=/d' \
		"${BUILD_DIR}/mkosi.extra/etc/environment" || true
	cat "${environment_proxy_snippet}" >>"${BUILD_DIR}/mkosi.extra/etc/environment"
fi

# 尽量保留宿主机 localtime（镜像运行时用），但避免影响 mkosi 构建阶段
if [ -f /etc/localtime ]; then
	mkdir -p mkosi.extra/etc/
	# -P: preserve symlink if /etc/localtime is a symlink
	sudo cp -P /etc/localtime mkosi.extra/etc/ || true
fi

mkdir -p ${BUILD_DIR}/mkosi.extra/etc/modules-load.d/
mkdir -p ${BUILD_DIR}/mkosi.extra/etc/chrony/
echo ptp_kvm >${BUILD_DIR}/mkosi.extra/etc/modules-load.d/ptp_kvm.conf
echo "refclock PHC /dev/ptp0 poll 2" >>${BUILD_DIR}/mkosi.extra/etc/chrony/chrony.conf

# apt_mirror="https://mirrors.ustc.edu.cn/ubuntu/"
apt_mirror="http://archive.ubuntu.com/ubuntu/"

# 镜像内 sources.list：用于 VM 运行时 + postinst
mkdir -p ${BUILD_DIR}/mkosi.extra/etc/apt
cat >${BUILD_DIR}/mkosi.extra/etc/apt/sources.list <<EOF
deb ${apt_mirror} jammy main restricted universe multiverse
deb ${apt_mirror} jammy-updates main restricted universe multiverse
deb ${apt_mirror} jammy-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
EOF

# remove snapshot-specific apt config
# (no mkosi.extra/etc/apt/apt.conf.d/99snapshot.conf)

enable_systemd_service sshd
enable_systemd_service systemd-networkd
enable_systemd_service systemd-resolved
enable_systemd_service chrony

mkdir -p mkosi.extra/etc/sysctl.d/
tee mkosi.extra/etc/sysctl.d/99-kubernetes-cri.conf <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# -----------------------------
# 8G swap: first boot create + every boot enable
# -----------------------------
mkdir -p mkosi.extra/usr/local/sbin
cat >mkosi.extra/usr/local/sbin/setup-swapfile.sh <<'EOF'
#!/bin/bash
set -euo pipefail

SWAPFILE=/swapfile
SIZE_GIB=8
SIZE_BYTES=$((SIZE_GIB * 1024 * 1024 * 1024))

if swapon --noheadings --show=NAME 2>/dev/null | awk '{print $1}' | grep -qx "$SWAPFILE"; then
    exit 0
fi

if [ ! -e "$SWAPFILE" ]; then
    if command -v fallocate >/dev/null 2>&1; then
        fallocate -l "${SIZE_GIB}G" "$SWAPFILE" || true
    fi
    if [ ! -e "$SWAPFILE" ] || [ "$(stat -c%s "$SWAPFILE" 2>/dev/null || echo 0)" -lt "$SIZE_BYTES" ]; then
        dd if=/dev/zero of="$SWAPFILE" bs=1M count=$((SIZE_GIB * 1024)) status=none
    fi
fi

chmod 600 "$SWAPFILE"

if ! (blkid "$SWAPFILE" 2>/dev/null | grep -q 'TYPE="swap"'); then
    mkswap "$SWAPFILE" >/dev/null
fi
EOF
chmod 0755 mkosi.extra/usr/local/sbin/setup-swapfile.sh

mkdir -p mkosi.extra/etc/systemd/system

cat >mkosi.extra/etc/systemd/system/swapfile.swap <<'EOF'
[Unit]
Description=Swap File (/swapfile)

[Swap]
What=/swapfile

[Install]
WantedBy=swap.target
EOF

cat >mkosi.extra/etc/systemd/system/setup-swapfile.service <<'EOF'
[Unit]
Description=Ensure /swapfile (8G) exists and is formatted
DefaultDependencies=no
Before=swapfile.swap
Wants=swapfile.swap

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/setup-swapfile.sh

[Install]
WantedBy=swap.target
EOF

mkdir -p mkosi.extra/etc/systemd/system/swap.target.wants
ln -sf /etc/systemd/system/setup-swapfile.service mkosi.extra/etc/systemd/system/swap.target.wants/setup-swapfile.service
ln -sf /etc/systemd/system/swapfile.swap mkosi.extra/etc/systemd/system/swap.target.wants/swapfile.swap
# -----------------------------

mkosi_ver="$($mkosi_bin --version | awk '/mkosi/{ print $2 }')"
if ((mkosi_ver >= 9)); then
	mkosi_opts+=("--autologin")
fi

mkosi_opts+=("--remove-package" "linux-generic")
mkosi_opts+=("--remove-package" "linux-image-generic")
mkosi_opts+=("--remove-package" "linux-headers-generic")
mkosi_opts+=("--remove-package" "linux-tools-generic")
mkosi_opts+=("--remove-package" "linux-cloud-tools-generic")

mkosi_opts+=("-d" "ubuntu")
mkosi_opts+=("-r" "jammy")

mkosi_opts+=("build")

sudo -E env \
	"PATH=$PATH" \
	"http_proxy=${host_http_proxy}" \
	"https_proxy=${host_https_proxy}" \
	"HTTP_PROXY=${host_http_proxy}" \
	"HTTPS_PROXY=${host_https_proxy}" \
	"all_proxy=${all_proxy:-${ALL_PROXY:-}}" \
	"ALL_PROXY=${ALL_PROXY:-${all_proxy:-}}" \
	"no_proxy=${host_no_proxy}" \
	"NO_PROXY=${host_no_proxy}" \
	$mkosi_bin "${mkosi_opts[@]}"
sudo chmod go+rw root.img
cd -
